### ISSUE TITLE
NMDS: subscript out of bounds

### ISSUE THREAD

**Issue by sjanssen2** [jlab/FlowSoFineApp#10]
using these metadata
[help.csv](https://github.com/JonasKup/FlowSoFineApp/files/7302746/help.csv)
and this predefined experiment
[Skin Esser-FlowSoFine-2021-10-07.RData.zip](https://github.com/JonasKup/FlowSoFineApp/files/7302752/Skin.Esser-FlowSoFine-2021-10-07.RData.zip)
generating an NMDS Plot for `cage_number` fails with the above error message in the App
![image](https://user-images.githubusercontent.com/11960616/136377187-c535175e-d1c3-4b18-af89-c1b3530497e0.png)
and this on the console
```
Warning in complete.cases(pts) & !is.na(groups) :
  longer object length is not a multiple of shorter object length
Warning: Error in [: subscript out of bounds
  170: ordispider
  169: renderPlot [/home/sjanssen/miniconda3/envs/flowsofine_4/lib/R/library/FlowSoFineApp/shiny-app/FlowSoFineApp/R/nmds_tab.R#68]
  167: func
  127: drawPlot
  113: <reactive:plotObj>
   97: drawReactive
   84: renderFunc
   83: output$nmdsTab-nmdsPlot
    2: shiny::runApp
    1: launchApp
```

**Comment by sjanssen2** [comment]
oh, I figure my metadata file had more rows than I had samples in the experiment :-/
Can you please trigger an according warning if this is really the cause for this error here?

**Comment by JonasKup** [comment]
There is now a check so that the number of rows in the metadata table and the number of .fcs files have to match. Also empty strings in the metadata table are automatically replaced with missing values as empty strings also resulted in crashes.

**Comment by sjanssen2** [comment]
and there will always be some empty values due to e.g. control samples or simply missing data --> therefore, great that you fixed in programmatically!
