### ISSUE TITLE
drag and drop wrong files

### ISSUE THREAD

**Issue by sjanssen2** [jlab/FlowSoFineApp#3]
https://github.com/JonasKup/FlowSoFineApp/blob/403591e8b334c09e919e911c85f94f770162e229/inst/shiny-app/FlowSoFineApp/R/newProject_tab.R#L17-L19

I am able to drag and drop non *.fcs files into the file box :-/
![image](https://user-images.githubusercontent.com/11960616/136372967-894add39-ea7f-447a-8a74-aef7125d341a.png)
Can we prevent that? 

I got a warning on the console, but not within the APP
`Warning: Error in readFCSheader: This does not seem to be a valid FCS2.0, FCS3.0 or FCS3.1 file`

**Comment by JonasKup** [comment]
Added check for correct filetypes and added a popup with a warning
![grafik](https://user-images.githubusercontent.com/53520351/136693325-188d9b0a-6814-4a6b-94f5-60db590e4f1b.png)
