### ISSUE TITLE
\t as seperator

### ISSUE THREAD

**Issue by sjanssen2** [jlab/FlowSoFineApp#5]
https://github.com/JonasKup/FlowSoFineApp/blob/403591e8b334c09e919e911c85f94f770162e229/inst/shiny-app/FlowSoFineApp/R/newProject_tab.R#L17-L19

Often, "spreadsheet" data come with `\t` (tab) as separator. How could I define this "char" here?
The console says `Warning: Error in scan: invalid 'sep' value: must be one byte` when doing
![image](https://user-images.githubusercontent.com/11960616/136373692-02261440-ba87-4ca9-88b7-71f80836c126.png)

**Comment by JonasKup** [comment]
Annoyingly the textInput automatically adds another "\" to escape the initial "\" which leads to "\t" becoming "\\t" and the function not accepting it as a seperator anymore. I added a quick fix but this will not work if there are other commonly used seperators with a "\" prefix.

`if (sepText == "\\t") sepText <- "\t"`

Do you think a dropdown menu with commonly used seperators could work instead?

**Comment by sjanssen2** [comment]
this is rather a design decision than a technical issue: the more freedom you provide to the user, the more he/she can do / understand wrong. Thus, providing a free text field is dangerous. It might be better to use a combo box with a given set of options. I guess the most common separators are "\t", ";", "," and maybe space " ". Should be sufficient to provide these an fixed options.

**Comment by JonasKup** [comment]
implemented as suggested https://github.com/jlab/FlowSoFineApp/commit/d2a0a7160e5ce206a33a5740f02434bc807ec322
