### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by sjanssen2** [jlab/FlowSoFineApp#6]
How do I know from the table shown if a file can be used as a sample?

For example: I have uploaded ALL the files from this directory

![image](https://user-images.githubusercontent.com/11960616/136373868-78326a05-e027-4701-81d9-46cd48d165c2.png)

including the `Exp31.xml` and the `sampleID.xlsx` files
![image](https://user-images.githubusercontent.com/11960616/136374067-670d2350-9255-4689-9e26-d249f351326c.png)

https://github.com/JonasKup/FlowSoFineApp/blob/403591e8b334c09e919e911c85f94f770162e229/inst/shiny-app/FlowSoFineApp/R/newProject_tab.R#L116

**Comment by JonasKup** [comment]
Only .fcs files can be uploaded as samples now
