### ISSUE TITLE
Visualize -> sample view

### ISSUE THREAD

**Issue by sjanssen2** [jlab/FlowSoFineApp#9]
would "sample view" be a more speaking label instead of "visualize"?
![image](https://user-images.githubusercontent.com/11960616/136375991-9aa87801-f431-4b2f-9ad2-3a74877ed9b7.png)

**Comment by JonasKup** [comment]
Changed the name to "sample viewer"
![grafik](https://user-images.githubusercontent.com/53520351/136693356-4bf6806e-6af3-4637-affa-e6c56c50c262.png)

**Comment by sjanssen2** [comment]
great. thank you!
